modLoader="javafml"  
loaderVersion="[35,)"  
license="All Rights Reserved"   
issueTrackerURL=""  
 
[[mods]]  
modId="storymobs"  
version="1.0"  
displayName="Story Mobs"  
updateJSONURL=""  
displayURL=""  
logoFile=""  
credits="Vaguely Interesting for the art, GentWorm for writing the code"  
authors="Vaguely Interesting, GentWorm"  
description='''
This mod adds mobs from Minecraft:Story Mode into the game!
'''  